# Generated by cucumber-sinatra. (2010-11-20 14:31:06 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'myapp.rb')

require 'cucumber/web/tableish'
require 'capybara'
require 'capybara/cucumber'
#require 'rspec'

Capybara.app = Sinatra::Application.new

class BolthouseWorld
  include Capybara
  #include RSpec::Expectations
  #include RSpec::Matchers
end

World do
  BolthouseWorld.new
end
